/* Leitura do CSV e atualização do dashboard. A coluna TOTAL é sempre ignorada. */
(() => {
  // Drogas representa somente o peso (em gramas) das linhas MACONHA, CRACK e COCAÍNA.
  const categories = { carros:['carro'], motos:['moto'], armas:['arma'], drogas:['maconha','crack','cocaína','cocaina'], prisoes:['preso','prisão','prisao'], flagrantes:['flagrante'], tco:['tco'], boc:['boc'] };
  const state = { rows:[], days:[], dayMap:new Map(), selection:'all', startDate:null, endDate:null };
  const $ = (id) => document.getElementById(id);
  const normalize = (text) => String(text ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const number = (value) => { const cleaned = String(value ?? '').trim().replace(/\./g,'').replace(',', '.'); const parsed = Number(cleaned); return Number.isFinite(parsed) ? parsed : 0; };
  // Aceita cabeçalhos como "01", "01 dia" e "01/ago."; TOTAL nunca entra aqui.
  const isDay = (header) => /^(0?[1-9]|[12]\d|3[01])(?:\s*(?:dia|[/.\-]\s*[a-zç]{3,}\.?))?$/i.test(String(header).trim());
  const monthNumbers = { jan:0, fev:1, mar:2, abr:3, mai:4, jun:5, jul:6, ago:7, set:8, out:9, nov:10, dez:11 };
  function toDateKey(header) { const match=String(header).trim().match(/^(\d{1,2})\s*[/.-]\s*([a-zç]{3,})/i); if (!match) return null; const month=monthNumbers[normalize(match[2]).slice(0,3)]; if (month === undefined) return null; const date=new Date(new Date().getFullYear(), month, Number(match[1])); return date.toISOString().slice(0,10); }
  function setStatus(text, error=false) { const el=$('status'); el.textContent=text; el.className=`status${error?' error':''}`; el.style.display=text?'block':'none'; }
  function selectedFields() { if (state.selection === 'all') return state.days; return state.days.filter((day)=>{ const date=toDateKey(day); return date >= state.startDate && date <= state.endDate; }); }
  function sum(row) { return selectedFields().reduce((total, field) => total + number(row[field]), 0); }
  function metricData() { return Object.entries(categories).map(([id, keys]) => ({ id, label: document.querySelector(`#metric-${id}`).parentElement.querySelector('span').textContent, value: state.rows.filter((row) => keys.some((key) => normalize(row.PRODUTIVIDADE).includes(key))).reduce((total,row) => total+sum(row),0) })); }
  function update() { const rows = state.rows.map((row) => ({ label:row.PRODUTIVIDADE || 'Sem descrição', value:sum(row) })).filter((row) => row.label); const metrics=metricData(); metrics.forEach(({id,value}) => { $(`metric-${id}`).textContent=ProductivityCharts.formatNumber(value); }); ProductivityCharts.render(metrics); renderTable(rows); const selected=state.selection==='all'?'Todos os dias':`${formatDate(state.startDate)} até ${formatDate(state.endDate)}`; $('periodLabel').textContent=`Período selecionado: ${selected}`; $('valueHeading').textContent=selected; }
  const formatDate=(value)=>new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T12:00:00`));
  function renderTable(rows) { const term=normalize($('tableSearch').value); const filtered=rows.filter((row)=>normalize(row.label).includes(term)); $('tableBody').innerHTML=filtered.length ? filtered.map((row)=>`<tr><td>${escapeHtml(row.label)}</td><td class="numeric">${ProductivityCharts.formatNumber(row.value)}</td></tr>`).join('') : '<tr><td class="empty" colspan="2">Nenhum resultado encontrado.</td></tr>'; $('tableSummary').textContent=`${filtered.length} itens exibidos`; }
  const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,(char)=>({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[char]);
  function load(data) { const headers=Object.keys(data[0] || {}); const productField=headers.find((h)=>normalize(h).includes('produtividade')) || headers[0]; state.days=headers.filter((h)=>isDay(h) && !normalize(h).includes('total')); state.rows=data.map((row)=>({ ...row, PRODUTIVIDADE:row[productField] })).filter((row)=>row.PRODUTIVIDADE); if(!state.days.length) throw new Error('Não foi possível identificar as colunas de dias (01 a 31).'); state.dayMap=new Map(state.days.map((day)=>[toDateKey(day),day]).filter(([date])=>date)); const availableDates=[...state.dayMap.keys()].sort(); const start=$('startDate'); const end=$('endDate'); [start,end].forEach((input)=>{ input.min=availableDates[0]; input.max=availableDates.at(-1); }); start.value=availableDates[0]; end.value=availableDates.at(-1); state.startDate=start.value; state.endDate=end.value; const applyRange=()=>{ if(start.value > end.value) end.value=start.value; state.selection='range'; state.startDate=start.value; state.endDate=end.value; $('allDays').checked=false; update(); }; $('allDays').onchange=(event)=>{ [start,end].forEach((input)=>input.disabled=event.target.checked); if(event.target.checked) state.selection='all'; else applyRange(); update(); }; start.onchange=applyRange; end.onchange=applyRange; $('tableSearch').oninput=()=>renderTable(state.rows.map((row)=>({label:row.PRODUTIVIDADE,value:sum(row)}))); setStatus(''); update(); }
  function fetchCsv() { const url=window.DASHBOARD_CONFIG?.csvUrl; if(!url || url.includes('COLE_AQUI')) { setStatus('Configure a URL do CSV publicado em window.DASHBOARD_CONFIG, no arquivo index.html.', true); return; } const freshUrl=`${url}${url.includes('?') ? '&' : '?'}_=${Date.now()}`; Papa.parse(freshUrl,{ download:true, header:true, skipEmptyLines:true, beforeFirstChunk:(chunk)=>{ const lines=chunk.split(/\r?\n/); const headerAt=lines.findIndex((line)=>/^\s*"?DIA"?\s*[,;]/i.test(line)); return headerAt > 0 ? lines.slice(headerAt).join('\n') : chunk; }, complete:(result)=>{ if(result.errors.length) console.warn(result.errors); try { load(result.data); } catch(error) { setStatus(error.message,true); } }, error:()=>setStatus('Não foi possível carregar o CSV. Verifique se ele está publicado na web.',true) }); }
  fetchCsv();
})();
